server:
  port: 8080

spring:
  application:
    name: spark-data-analysis
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/analyseserver?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

# 文件上传配置
file:
  upload:
    max-size: 2199023255552
    allowed-types: csv,xlsx,xls,parquet
    base-path: ${user.dir}/data
    chunk-size: 10485760
    async-processing: true

spark:
  app-name: SparkDataAnalysis
  master: local[*]
  config:
    spark.driver.host: ${SPARK_DRIVER_HOST:localhost}
    spark.driver.bindAddress: ${SPARK_DRIVER_HOST:localhost}
    spark.driver.port: 10000
    spark.port.maxRetries: 100
    spark.driver.memory: 4g
    spark.executor.memory: 4g
    spark.sql.warehouse.dir: spark-warehouse
    spark.ui.enabled: false
    park.sql.shuffle.partitions: 10
    spark.memory.offHeap.enabled: true
    spark.memory.offHeap.size: 2g
    spark.sql.legacy.timeParserPolicy: LEGACY
logging:
  level:
    root: INFO
    sparkanalysis: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 